server:
  port: 8033
 
eureka:         
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://localhost:8035/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5
 
spring:    
  application:
    name: microcommerce
     
management:
  security:
    enabled: false  
 
logging:
  level:
    com.self.sprintboot.learning.employee: DEBUG