server:
  port: 8034    #port number
 
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://localhost:8035/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5
 
spring:    
  application:
    name: myMicroservice
     
management:
  security:
    enabled: false  
 
logging:
  level:
    com.self.sprintboot.learning.apigateway: DEBUG